/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: yanix (https://sketchfab.com/yanix)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/jellyfish-d06a5a553fe641ab92f720527b2278f3
title: jellyfish
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/scene.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions["ArmatureAction.001"]);
    actions["ArmatureAction.001"].play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.28}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <group scale={[3.63, 3.63, 3.63]} />
            <group scale={[3.63, 3.63, 3.63]} />
            <skinnedMesh
              geometry={nodes.Object_34.geometry}
              material={materials.jellyfish_body}
              skeleton={nodes.Object_34.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_37.geometry}
              material={materials.emit}
              skeleton={nodes.Object_37.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
