// ACTION TYPES FOR REGISTERSCREEN
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// ACTION TYPES FOR LOGINSCREEN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// ACTION TYPES FOR LOGOUT
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// ACTION TYPES GLOBALLY SET USER
export const SET_USER = "SET_USER";

// ACTION TYPES FOR GOOGLE
export const GOOGLE_START = "GOOGLE_START";
export const GOOGLE_SUCCESS = "GOOGLE_SUCCESS";
export const GOOGLE_FAIL = "GOOGLE_FAIL";

// ACTION TYPES FOR FB
export const FB_START = "FB_START";
export const FB_SUCCESS = "FB_SUCCESS";
export const FB_FAIL = "FB_FAIL";
